# Utility help targets
.PHONY: help-l help-c help-vs help-r help-pm

help-l:
	@echo "Generate requirements.lock file"
	@echo "Usage: make l"
	@echo ""
	@echo "This target generates a requirements.lock file:"
	@echo "1. Uses pip-tools to generate a lock file"
	@echo "2. Includes all dependencies with exact versions"
	@echo "3. Adds system-specific packages"
	@echo ""
	@echo "WARNING: The generated lock file is machine-specific!"
	@echo "Do not commit this file to version control."
	@echo ""
	@echo "For other systems:"
	@echo "- Ubuntu/Debian: Use requirements.lock.ubuntu"
	@echo "- macOS: Use requirements.lock.macos"
	@echo "- Windows: Use requirements.lock.windows"

help-c:
	@echo "Check Python environment"
	@echo "Usage: make c"
	@echo ""
	@echo "This target checks your Python environment:"
	@echo "1. Verifies Python version"
	@echo "2. Checks virtual environment"
	@echo "3. Reports any compatibility issues"
	@echo ""
	@echo "The Python version is determined by PYTHON_VERSION in your environment file"
	@echo "Other versions may work but are not tested"

help-vs:
	@echo "Create Darwin vector store"
	@echo "Usage: make vs"
	@echo ""
	@echo "This target creates a vector store from Darwin correspondence XML files:"
	@echo "1. Sets up a virtual environment"
	@echo "2. Installs required dependencies"
	@echo "3. Processes Darwin letter XML files"
	@echo "4. Creates embeddings and stores them"
	@echo ""
	@echo "Required:"
	@echo "- Darwin XML files in darwin_sources_TEST/xml/"
	@echo "- CSV metadata in darwin_sources_TEST/csv/"
	@echo "- Sufficient disk space for the vector store"
	@echo "- Python version specified in your environment file"

help-r:
	@echo "Generate Darwin retriever"
	@echo "Usage: make r"
	@echo ""
	@echo "This target generates a retriever for the Darwin vector store:"
	@echo "1. Sets up a virtual environment"
	@echo "2. Installs required dependencies"
	@echo "3. Creates Darwin retriever configuration"
	@echo "4. Generates retriever with direction and time period filtering"
	@echo ""
	@echo "Required:"
	@echo "- Darwin vector store must exist (run 'make vs' first)"
	@echo "- Python version specified in your environment file"


help-pm:
	@echo "Prepare embedding model for Darwin ATLAS"
	@echo "Usage: make pm"
	@echo ""
	@echo "This target prepares the embedding model for use with Darwin ATLAS:"
	@echo "1. Downloads the base model if not present"
	@echo "2. Converts to Sentence-Transformer format"
	@echo "3. Sets up the pooling strategy"
	@echo "4. Saves to the models directory"
	@echo ""
	@echo "Required:"
	@echo "- EMBEDDING_MODEL environment variable (default: Livingwithmachines/bert_1760_1900)"
	@echo "- POOLING environment variable (default: mean)"
	@echo "- Python version specified in your environment file"
	@echo ""
	@echo "After running:"
	@echo "1. The model will be available in the models directory"
	@echo "2. The model will be used automatically by the Darwin retriever"
	@echo "3. Vector store creation will skip model preparation" 